### ISSUE TITLE
Missing og:image after refactor

### ISSUE THREAD

**Issue by marcelpinto** [unfolding-io/StarFunnel#8]
After refactor in https://github.com/unfolding-io/StarFunnel/commit/b926fc5e8bd821a8041951c8e76eed9c2bf944f7#diff-dfa302770ad2aae54fd1f482d4510a6589b556f592f7ceae8dbb73725d4ef0e1 the socialImage is always null, meaning it won't add the og:image or twitter tags.

I tried to use the `getImage` from astro:assets but the build fails then

```
const socialImage = !!thumbnail
  ? Astro.url.origin + (await getImage({ 
    src: thumbnail,
    width: 1200,
    height: 630,
  })).src
  : null;
```

Any idea how to restore this functionality?

Error:

```
 generating optimized images 
ENOENT: no such file or directory, open '.../dist/src/assets/og_image.png'
  Stack trace:
    at async open (node:internal/fs/promises:639:25)
    at async loadImage (file:///.../node_modules/astro/dist/assets/build/generate.js:187:11)
    at async generatePages (file:///.../landing/node_modules/astro/dist/core/build/generate.js:136:7)
    at async AstroBuilder.build (file:///.../landing/node_modules/astro/dist/core/build/index.js:133:5)
    at async build (file:///..../landing/node_modules/astro/dist/core/build/index.js:45:3)
```

**Comment by preetamslot** [comment]
good catch, will fix asap.

**Comment by preetamslot** [comment]
Fixed
